Rm unnecessary, wrongly typed arg to ana/error
This causes

> ClassCastException: class clojure.lang.PersistentArrayMap cannot be cast to class java.lang.Throwable

instead of the expected

> Encountered error when macroexpanding com.fulcrologic.fulcro.routing.dynamic-routing/defrouter.
defrouter options are invalid: {:router-targetsXXX [Main]}

The 3rd argument to ana/error should be the cause, i.e. a Throwable.